### ISSUE TITLE
Concurrent Middleware

### ISSUE THREAD

**Issue by Bogh** [gorilla/muxy#15]
Hi,

I would like to help with your development if it's possible and  I've also been thinking, if it's worth having, concurrent middleware. If the middleware function returns a channel then it will be a concurrent middleware and the Handle will be executed when all concurrent middleware finished.

**Comment by elithrar** [comment]
Can you expand on the use-case for concurrent middleware?

*http.Request cannot be modified concurrently, and you can't have multiple
writes to http.ResponseWriter

**Comment by Bogh** [comment]
There might be some cases where middleware might have nothing to do with the http.ResponseWriter, and could be done concurrently. But if this cases are rare might not be worth the trouble.

**Comment by elithrar** [comment]
In those events you could still write them, but exposing that in muxy is
unlikely to be beneficial.

**Comment by Bogh** [comment]
Right. :)
I just realize. I'm still new to all concurrency thinking. Ty.
