### ISSUE TITLE
need a parser!

### ISSUE THREAD

**Issue by moraes** [gorilla/muxy#2]
My time to code is very limited, so would anybody help transforming `parse()` here into a real, efficient string parser?

http://play.golang.org/p/BPZ2KX6SsB

Sorry for the quick hack. :pensive:

**Comment by garyburd** [comment]
To make it easier to add features in the future, there should be limits on what's allowed in the {}. For example, we can say that the part must be "*" or a valid Go identifier.

**Comment by moraes** [comment]
> To make it easier to add features in the future, there should be limits on what's allowed in the {}.

Indeed. I added a basic parser that accepts `*` or a Go identifier for variable names.

**Comment by garyburd** [comment]
Oh,  I was going to offer to do it after the spec was clear.  Do you still want help with this?

**Comment by moraes** [comment]
It's ok. I'm not particularly happy with this one, but this is not critical as long as it parses correctly.

**Comment by moraes** [comment]
I compared your parse function with the current one and got this numbers:

	BenchmarkParseOLD      1000000              1418 ns/op             144 B/op          1 allocs/op
	BenchmarkParseNEW      1000000              2052 ns/op             368 B/op          4 allocs/op

Removing `append()` (creating the parts slice previously with a length of the number of separators found, and using indexes to set each part) improves it a bit:
	
	BenchmarkParseNEW      1000000              1439 ns/op             144 B/op          1 allocs/op

Anyway, this is not a place where we want to squeeze the numbers a lot. This is compile time, not execution time. So please submit your parser again, because the percent decoding thing will be a good addition.

**Comment by garyburd** [comment]
I'll submit PR with percent decoding soon.
