### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by elithrar** [gorilla/muxy#4]
Some questions to get the ball rolling on this:
- What signature should we accept? 
- Single middleware? Variadic?
- Where does the method sit?

Also take a look at what [alice](https://github.com/justinas/alice) and [negroni](https://github.com/codegangsta/negroni) do—although I think the latter is too centered on its own `HandlerFunc` type to be useful.

---

My thoughts:
- My experience here is that `func(http.Handler) http.Handler` has become the 'defacto' standard.
- Variadic. Chaining `Use(auth).Use(csrf).Use(logging)` is clunky and serves little benefit.
- `router.Use(middleware ...func(http.Handler) http.Handler)` — keep it simple.

Middleware should apply to all routes below it (no exceptions), and sub-routers (however they shake out) should be able to apply additional middleware (e.g. auth) of their own.

**Comment by moraes** [comment]
1. I haven't thought about the signature and will accept any proposal derived from your investigations (simpler is better). However we are currently using `func(http.ResponseWriter, *http.Request)` as handler, so the signature that would fit would be `func(func(http.ResponseWriter, *http.Request)) func(http.ResponseWriter, *http.Request)`. It's clunky-looking but plausible, I guess;
2. A variadic function would be fine, probably taking the same decision from [alice's author](https://justinas.org/alice-painless-middleware-chaining-for-go/): apply them in the same order they were declared. So, following the same rule, a subrouter that gets extra middleware would apply the extra ones after the inherited ones, etc. Would this be fine?;
3. I want to minimize duplicated methods, and so I guess `.Use` would be placed in Router (and eventually in Subrouter). For single routes, the handler can be wrapped in the existing method calls;

Note: the final form of Muxy's subrouters is not set, but it's clear for me that they will not be nested, I mean, there will be no router calling child router or accessing parent router properties etc. That's 100% unnecessary complication and overhead: instead, the subrouter will be able to register routes with common properties (pattern and name suffix, middleware, etc) or a Router will accept registering a router on a mount point and re-register its routes. In other words: internally it will result in a flat, single router structure (does it make sense?).

**Comment by elithrar** [comment]
1. Much of the [gorilla/handlers](https://github.com/gorilla/handlers) package subscribes to the `func(http.Handler) http.Handler` sig, and a lot of middleware "in the wild" is the same. It's easy enough to write a simple wrapper that way - e.g.

```go
func SomeMiddleware(h http.Handler) http.Handler {
    fn := func(w http.ResponseWriter, r *http.Request) {
        // do things
        h.ServeHTTP(w, r)
        return
    }
    return http.HandlerFunc(fn)
}
```

You can also write more complex middleware by satisfying `http.Handler` with a custom type - [see here](https://github.com/gorilla/csrf/blob/master/csrf.go#L53-L58)

2. Agreed - same order as declared (left to right).
3. That sounds good to me.

**Comment by moraes** [comment]
Basic middleware support added on f10905d99bfb42de0441d0f78943e26dc9cb15cc. Contrary to what I said previously, it was added to Route, because the Router doesn't need to know about it. Subrouters are a different subject, but they are not defined yet.

Review, comments and tests needed.

**Comment by elithrar** [comment]
If we apply middleware to a `*Route` instead of a `*Router` it's only mildly different from the below:

```go
router.Get("/", IndexHandler).Use(CSRF, Logging)
router.Get("/form", FormHandler).Use(CSRF, Logging)
router.Post("/form", SubmitHandler).Use(CSRF, Logging)
// etc.
```

Instead, we should apply it to a the `*Router` (and `Subrouter`?) so you can do the following:

```go
router.Use(CSRF, Logging)
// Automatically applied to all routes on this router
router.Get("/", IndexHandler)
```

In many cases you want to apply logging, CSRF prevention, CORS, etc. to all routes (or sub-routes) within an application rather than on  a route-by-route basis. If you want to apply it that way you can just wrap individual routes as-needed.

**Comment by davidkuridza** [comment]
+1 for @elithrar's `*Router` and `Subrouter` idea.

**Comment by moraes** [comment]
You guys are right. This was the plan. So `.Use()` was moved to Router,now there is a better setup for subrouters:

- Router now carries the middleware list;
- Router also serves as subrouter, avoiding some API overhead;
- Additionaly to setting shared middleware, a subrouter can be used to set pattern and name prefixes.

The current subrouter setup is close to what I think it should be in terms of API and behavior, but it doesn't cover the second use case for subrouters which is "importing routes from a router defined in a different package". This will require extra API and offer a middleware dilemma that I will describe soon.

**Comment by moraes** [comment]
I've been thinking about these things lately:

1. muxy should not provide a Matcher implementation. It becomes a 200 LOC "router framework" and "official" Matcher implementations are provided in the muxy/matchers subdirectory;
2. muxy should not implement middleware chains etc: it is about routing only and middleware is left to specialized packages. For example, http://github.com/andviro/noodle;
3. I **really** would like to use net/context to store route variables, because a context solves a lot more things than providing URL variables, and I'm trying to balance the best way to do this;
4. A bold move would be to adopt [noodle.Handler](https://github.com/andviro/noodle/blob/master/core.go#L13). This would solve `#2` and `#3`.

**Comment by elithrar** [comment]
My concern with noodle - which I raised here as well: https://github.com/goji/goji/issues/7#issuecomment-162728605 - is that you can't redefine the error handling on `noodle.Handler`. In a mixed environment where something accepts a `http.Handler` and therefore calls `ServeHTTP,` the `ServeHTTP` method on `noodle.Handler` ignores the returned error, which is certainly not what you want (ever?!). The `error` returned from `noodle.Handler` only applies in a chain - the end handler only gets to `return nil`, which is very confusing.

Package users may want to handle errors in their own way. Many existing applications don't return an error from their handler at all - `func(w http.ResponseWriter, r *http.Request)` is pretty pervasive.

Given that muxy is a clean break from mux (which can continue to support non-contextified handlers) I'd suggest supporting:

* `func(context.Context, http.ResponseWriter, *http.Request)` as a first-class citzen and the *default* handler (aka `muxy.HandlerFunc`)
* A `muxy.Handler` type that looks like the following, and which no. 1 implements:

```go
type Handler interface {
    ServeHTTPC(context.Context, http.ResponseWriter, *http.Request)
}

type HandlerFunc func(context.Context, http.ResponseWriter, *http.Request)

// By providing a ServeHTTP method, muxy.Handlers can still be used where only a http.Handler is supported, which is still a LOT of the Go ecosystem. Further, if Go 1.7 *does* put context.Context inside request, migration/compatibility is made a lot simpler.
func (h HandlerFunc) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h(context.TODO(), w, r)
}

func (h HandlerFunc) ServeHTTPC(c context.Context, w http.ResponseWriter, r *http.Request) {
	h(c, w, r)
}
```

* I still think muxy should support adding a middleware chain at a router level, but I'd probably limit this to *one* method on `*Router` only to keep the API as slim as possible. I can see the value in offloading to external packages if need be.

Hope that's coherent! :speak_no_evil:

**Comment by andviro** [comment]
Well, these are fair points and in https://github.com/goji/goji/issues/7 I've expressed some of my thoughts regarding whether to return error or not. 
Personally, I'd say that as a router, accepting HandlerFunc interface as outlined above is the most prudent way to go. This way, other middlewares and frameworks would just have to implement ServeHTTPC method and remain compatible. I'm totally ok with it.

On the other hand, if you guys will start to implement subrouters integrated with middleware chains, i.e. something like that:
```go
r := NewRouter()
r.Use(GlobalMiddleware)
apiGroup := r.Group("/api")
apiGroup.Use(ApiMiddleware, RenderMiddleware)
apiGroup.Get("/", ListHandler)
```
I heartily welcome you to use noodle.Chain as a base. It's designed just with this use case in mind, chains are easy to break off at any point and become separate chains. Hence noodle, BTW.

**Comment by moraes** [comment]
Thanks for the thoughtful comments. I agree that a `Handler` interface with `ServeHTTPC` is the most appropriate way to support net/context and have made the related changes.

I had the same feeling about the error returned from `noodle.Handler`, because it is not just a "context-aware version of net/http.Handler"; it crosses the line a little bit. If noddle maintains that signature, users can define a wrapper for muxy:

```go
// noodleHandler is a context-aware HTTP handler function that returns an error
// for appropriate error handling in middleware chains.
type noodleHandler func(context.Context, http.ResponseWriter, *http.Request) error

// ServeHTTPC calls h(c, w, r).
func (h noodleHandler) ServeHTTPC(c context.Context, w http.ResponseWriter, r *http.Request) {
	h(c, w, r)
}
```

The current problem to integrate middleware is how to behave when `muxy.Mount()` is used. The mounted routes may have some middleware applied already, and subrouters could apply the same middleware again. Unless we change how `muxy.Mount()` works, or don't use preexisting middleware from the mounted routes (which can be unexpected), I don't know how to solve it. 

Maybe, instead of `Mount`, an iterable could be provided to import routes from a router. This complicates things a little bit, but then users can decide if they use existing middleware or not.

**Comment by andviro** [comment]
Ah, I see. I need a moment to think about it. Currently I'm trying to knock together some kind of simple router with groups/subrouters based on httprouter or muxy. I'll have to see what will come out of it, and then'll try to make myself useful here.

**Comment by moraes** [comment]
@andviro , it would be so nice if you implement it as a muxy.Matcher! Of course I'll be opened to your suggestions regarding the Matcher interface, the general API and how middleware should go in.

Middeware groups in muxy should be easy to implement, except for the `Mount()` dilemma. For this reason, maybe `Mount()` shouldn't be there -- or the functionality should be provided in a different manner.

**Comment by andviro** [comment]
Hello all. I've put together some simple middleware-oriented mux based on http router: https://github.com/andviro/wok. Sorry for not using muxy there, but I had more luck with httprouter at the moment. What may or may be not useful is the way router groups are handled: dead simple, just make a separate router that handles HTTP the usual way and make it handle group prefix. Per-group middlewares are no-brainer too: just compose final handler before attaching it to the respective endpoint.

**Comment by moraes** [comment]
Hey, @andviro. I think your "Group prefix should not have parameters" limitation makes groups a bit less useful and could be avoided if you didn't use different httprouter instances.

muxy is not a full router without a matcher implementation (coming soon, in a separate package), so I understand your choice. Feasible.

As per initial plan, it (now) has a simple mechanism to manage middleware, which can be ignored if you use a specialized middleware library. Middleware can be attached to the main router or groups (which inherit the middleware from upper router or groups). Per handler middleware has no special mechanism; you just wrap the handler:

```go
// Create a new router and attach 3 middleware to it:
r = muxy.New(matcher).Use(Middleware1, Middleware2, Middleware3)
// Create a group for path prefix "/admin" and attach 2 more middleware to it.
// Groups "inherit" the middleware attached to the parent router or group:
g := r.Group("/admin").Use(Middleware4, Middleware5)
// Add group handlers for GET and POST with an additional middleware. 
// It will inherit the 5 middleware we added before:
g.Route("/users").Get(Middleware6(listUsers)).Post(Middleware6(updateUsers))
```

**Comment by andviro** [comment]
The idea not to use separate httprouter is brilliant! Thank you very much, @moraes, you're a genius. It allowed me to further simplify the code in https://github.com/andviro/wok/commit/eb0b113c9ae0ed04b57011522642ef71851fec19.  
As for your decision to use a bit more verbose chained .Handle invocation syntax, FWIW I don't think it's too verbose or counterintuitive, except that intuitively I expected to see HTTP method name a first parameter not the last.

**Comment by moraes** [comment]
String methods are a variadic argument in `Route.Handle()`. The usefulness is questionable, indeed, but I never thought about it until you questioned it. I may take another look at it.

I'm considering accepting `interface{}` in the convenience methods. Then the passed parameter could be an ordinary function (with the proper signature) or `muxy.Handler`. Anything else would panic.

**Comment by moraes** [comment]
> The usefulness is questionable, indeed, but I never thought about it until you questioned it.

Ah, no. I just remembered the reason. You may want to handle any method, so that's why methods are variadic. `Route.Handle`is also for those that want to handle any method.

**Comment by andviro** [comment]
Oh, I see. The idea with polymorphic parameter is compelling, I thought about it in noodle. Still on the fence: ease of use vs static typing.
