### ISSUE TITLE
recommends supporting these routes

### ISSUE THREAD

**Issue by woniu369** [gorilla/muxy#9]
```
/{a}-{b}
/{a}_{b}
/{a}.{b}
/a{b}/{c}
```

**Comment by moraes** [comment]
This is possible... At the cost of performance.

I want to make the matcher interface public to allow matchers that are less minimalist than the built in one. In this plan, a matcher will be responsible for registering routes, matching requests, extracting variables and building URLs.

What you are asking here is a good candidate for an alternative matcher.
